import { Task } from '../types';

// Plantilla estandar de tareas que se inyecta al instalar la aplicacion
// (y al crear una nueva oportunidad sin snapshot personalizado).
// Los IDs son estables y se referencian entre si via dependsOnTaskIds —
// no cambiarlos sin re-apuntar las dependencias.
export const STANDARD_TASKS: Partial<Task>[] = [
    {
        id: "26b5fe04-646c-47e0-9852-02ef457e7fb0",
        title: "Set up Tender Control",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "d776aaa5-58c3-46f4-b202-ccf12daf318e", title: "Description of the Request", completed: false },
            { id: "aa2eee1a-e683-437b-a1f7-cc26ff6c1a76", title: "SRLink", completed: false },
            { id: "89e9da23-0399-4025-83ad-2b351173909f", title: "OPLink", completed: false },
            { id: "846498f7-2da8-40cc-b181-136e0ae88d12", title: "The first note in history", completed: false },
            { id: "efbf9343-33cd-46c2-8603-6ff5d8fdd9f5", title: "Set up KPIs", completed: false }
        ],
        order: 1,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "73edcadb-2302-4475-8407-9b257a3ff766",
        title: "Create Quotelink number and link to SR",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 2,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "394d612e-6c8f-4c70-8199-8244acaa8928",
        title: "Set up and manage project folder",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "f5083608-9101-48ba-a58d-9138b6fc7312", title: "Create the folder", completed: false },
            { id: "88b42afa-36b3-43e8-8aae-08f1cc41815e", title: "Enter the email address of the SR", completed: false }
        ],
        order: 3,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "53d004f2-a6b1-4fa2-beb9-3ac5e007c095",
        title: "Download CQA Import and Doc Template",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "c9d9039a-ef02-4a2c-a5e3-eba2e49fc37a", title: "CQA template", completed: false },
            { id: "e40a2c6c-8bd7-426e-8179-cf003b525896", title: "Doc Template", completed: false }
        ],
        order: 4,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "46bba0db-c4dd-4647-ae31-9a26f1344bd9",
        title: "Email structure setup",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 5,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: true
    },
    {
        id: "d27e7e05-7e26-4724-844a-d146fdc0cad1",
        title: "Create SR for TSC support",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "ed23497e-9713-4a15-8124-574ec87a293e", title: "TSC", completed: false },
            { id: "7652253b-f055-4a64-92d5-09e48940f693", title: "Delivery", completed: false },
            { id: "17330749-8321-4b6c-91cb-5a5fc6406d4f", title: "SCM", completed: false },
            { id: "d850302a-c9da-45dc-97c1-f93cbf9d4eb0", title: "Other", completed: false }
        ],
        order: 6,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "0d86163a-bd8d-43b4-a0c2-cc3530e15979",
        title: "TSC Assigned to Opportunity",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 7,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "d52448ad-1db4-4218-81c3-1f6572b90f13",
        title: "Review available information",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 8,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "4520d51c-4b11-4a66-a5f6-5ed39a9c45ec",
        title: "Check if there is an MSA or/and CFA.",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "External Area",
        externalAreas: ["Other", "Sales"],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 9,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "bc7378ee-afe5-47a7-9d3f-9e922a2fe8fa",
        title: "Publish CQA",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 10,
        dependsOnTaskIds: ["73edcadb-2302-4475-8407-9b257a3ff766"],
        blockDoneUntilDependenciesDone: true,
        calendarized: false
    },
    {
        id: "453c7749-5a6c-4cbf-9931-6645f4ef6160",
        title: "Receive the BOM",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "External Area",
        externalAreas: ["TSC"],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 11,
        dependsOnTaskIds: ["0d86163a-bd8d-43b4-a0c2-cc3530e15979"],
        blockDoneUntilDependenciesDone: true,
        calendarized: false
    },
    {
        id: "24d8876f-fc0c-48f4-a60e-4cae21a1f9ff",
        title: "KOM",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 12,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "f6c863ff-d6ad-406f-908e-8641720f364d",
        title: "PLAN AND SCHEDULE TASKS",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 13,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "13e223c4-7e29-4f1e-b7cc-7e2d139bd876",
        title: "Generate/Finalize BOM (BuyAutomation)",
        description: "",
        status: "Pending",
        priority: "High",
        owner: "External Area",
        externalAreas: ["Delivery", "TSC"],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 14,
        dependsOnTaskIds: ["453c7749-5a6c-4cbf-9931-6645f4ef6160"],
        blockDoneUntilDependenciesDone: true,
        calendarized: false
    },
    {
        id: "0609807c-60d5-4a1f-8f5e-91fec111f80d",
        title: "Request for Resales",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 15,
        dependsOnTaskIds: [
            "453c7749-5a6c-4cbf-9931-6645f4ef6160",
            "13e223c4-7e29-4f1e-b7cc-7e2d139bd876"
        ],
        blockDoneUntilDependenciesDone: true,
        calendarized: false
    },
    {
        id: "94e53656-d29b-4b71-a93c-e4ec01429e24",
        title: "Generate Preliminary Draft Proposal",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 16,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "f09e6c00-5c6b-4942-94e4-7b0f9ae8d49f",
        title: "Create preliminary GEET for Delivery",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "External Area",
        externalAreas: ["TSC", "Other"],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 17,
        dependsOnTaskIds: ["13e223c4-7e29-4f1e-b7cc-7e2d139bd876"],
        blockDoneUntilDependenciesDone: true,
        calendarized: false
    },
    {
        id: "6fc993c7-9d24-4ed2-8587-911f8cdb7cbc",
        title: "Initial fill up PACost",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "87411f22-7e3b-415e-9f38-2da3e47e4f83", title: "BOM Charged", completed: false }
        ],
        order: 18,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "fddfd57e-f397-4045-9680-5e54ea705480",
        title: "GEET Approval (Services - T&L)",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "External Area",
        externalAreas: ["Delivery", "SCM", "Sales", "TSC", "Other"],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 19,
        dependsOnTaskIds: ["f09e6c00-5c6b-4942-94e4-7b0f9ae8d49f"],
        blockDoneUntilDependenciesDone: true,
        calendarized: false
    },
    {
        id: "9667ab26-e47d-43d1-8cdf-6873a9cbdc83",
        title: "Consolidate costing (PACost)",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "External Area",
        externalAreas: ["Delivery", "Sales"],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "72f4e05d-30fc-4ff0-8f85-e11cc1a854c0", title: "BOM Charged", completed: false },
            { id: "ce3153c3-1ef4-4eb9-ad14-1cd6309b7435", title: "Delivery Hours charged", completed: false },
            { id: "38dc5da9-1cc2-41d6-82a7-594e1854ca6d", title: "Discounts charged", completed: false },
            { id: "107d12c0-4520-4514-9b7e-c9c265dd48c8", title: "Terms and condition", completed: false }
        ],
        order: 20,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "6188ecce-7641-40d6-a247-91286fb04bbb",
        title: "CQA Costing Consolidation",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 21,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "0b559707-8be4-45f3-b190-89cd0cb953f5",
        title: "Price approval",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 22,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "c4d61405-b9da-4aa9-bbf1-f67104498d1c",
        title: "Send the draft",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 23,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "ba5b43ba-8253-40e4-8259-7ad2b434fbde",
        title: "Approval draft",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 24,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "21fc90c9-2c47-4d6e-8bcf-71dcfe1acd72",
        title: "Update date and table of contents",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [
            { id: "36477679-38bc-424c-8cf5-508196dd546d", title: "Table", completed: false },
            { id: "55156d78-83a8-406c-b9a4-4843b68acf8a", title: "Date", completed: false }
        ],
        order: 25,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "9e765b72-4662-4a1a-af92-cb1cec780c56",
        title: "Convert to PDF and send to Sales",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 26,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "31954685-49bf-4956-94b5-1f08c1a91030",
        title: "Update the emails in the folder",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 27,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "07156ac3-e58a-4dc5-a658-516609c742fe",
        title: "Close the SR",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 28,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    },
    {
        id: "b39331f2-5952-4df4-9929-79e45b344981",
        title: "Update the amount and the quote link.",
        description: "",
        status: "Pending",
        priority: "Medium",
        owner: "Me",
        externalAreas: [],
        responsible: "",
        dueDate: "",
        subtasks: [],
        order: 29,
        dependsOnTaskIds: [],
        blockDoneUntilDependenciesDone: false,
        calendarized: false
    }
];
